#!/usr/bin/env python3
from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent
FIG = ROOT / "figures"
SRC = ROOT / "source_data"
OUT_CSV = SRC / "nature_physics_submission_asset_audit.csv"
OUT_MD = ROOT / "nature_physics_submission_asset_audit.md"


MAIN_FIGURES = [
    "nphys_fig1_memory",
    "nphys_fig2_boundary",
    "nphys_fig3_two_channel",
    "nphys_fig4_breathing_mechanism",
    "nphys_fig17_return_map_phase_portrait",
]

EXTENDED_FIGURES = [
    "nphys_fig15_route_phase_space",
    "nphys_fig8_long_cycle_true_force_memory",
    "nphys_fig21_force_loop_robustness",
    "nphys_fig16_dimensionless_loop_collapse",
    "nphys_fig25_loop_onset_susceptibility",
    "nphys_fig64_route_generality_true_force_extension",
    "nphys_fig18_nonreciprocal_transient_map",
    "nphys_fig23_minimal_state_sufficiency",
    "nphys_fig49_five_route_breath_memory_spectrum",
    "nphys_fig22_experimental_prediction_matrix",
]

SUPPLEMENT_FIGURES = [
    "fig5",
]

RESERVE_FIGURES = [
    "nphys_fig10_unified_projection",
    "nphys_fig27_loop_susceptibility_kernel",
    "nphys_fig28_readout_orthogonality",
    "nphys_fig29_training_order_parameter_flow",
    "nphys_fig30_breathing_phase_diagram",
    "nphys_fig31_two_scale_response_collapse",
    "nphys_fig32_dynamical_mode_alignment",
    "nphys_fig33_preparation_susceptibility",
    "nphys_fig34_fluctuation_response_bridge",
    "nphys_fig35_force_loop_precursor",
    "nphys_fig36_causal_path_audit",
    "nphys_fig37_breathing_quality_factor",
    "nphys_fig38_overload_observability",
    "nphys_fig39_lyapunov_storage",
    "nphys_fig40_force_loop_rare_events",
    "nphys_fig41_force_loop_rare_event_precursor",
    "nphys_fig42_breathing_memory_kernel",
    "nphys_fig43_force_loop_enrichment",
    "nphys_fig44_breathing_memory_cost_tradeoff",
    "nphys_fig45_return_map_normal_form",
    "nphys_fig46_force_loop_conduit_gating",
    "nphys_fig47_force_network_snapshot_plate",
    "nphys_fig48_force_loop_spatial_fingerprint",
    "nphys_fig68_force_filtration_topology",
    "nphys_fig69_force_filtration_shuffle_null",
    "nphys_fig26_breathing_response_function",
    "nphys_fig50_two_scale_variance_partition",
    "nphys_fig51_route_susceptibility_atlas",
    "nphys_fig52_phase_displacement_geometry",
    "nphys_fig53_phase_circulation_geometry",
    "nphys_fig54_phase_circulation_order_null",
    "nphys_fig55_phase_circulation_coordinate_robustness",
    "nphys_fig56_phase_circulation_writing_time",
    "nphys_fig57_phase_circulation_synthesis",
    "nphys_fig58_loop_predictive_information",
    "nphys_fig59_loop_information_binning_robustness",
    "nphys_fig60_loop_information_bias_corrected",
    "nphys_fig61_two_scale_information_decomposition",
    "nphys_fig62_state_closure_memory_depth",
    "nphys_fig63_route_generality_candidates",
    "nphys_fig20_mechanism_hierarchy_audit",
    "nphys_fig65_breathing_vital_signs",
    "nphys_fig66_breathing_component_necessity",
    "nphys_fig67_eight_route_hot_breath_cost",
]

MANUSCRIPT_FILES = [
    "thermal_ratcheting_nature_physics.tex",
    "thermal_ratcheting_nature_physics.pdf",
    "thermal_ratcheting_supplement.tex",
    "thermal_ratcheting_supplement.pdf",
    "nature_physics_extended_data_figures.tex",
    "nature_physics_extended_data_figures.pdf",
    "nature_physics_extended_data_captions.md",
    "nature_physics_claim_to_evidence_map.md",
    "nature_physics_extended_data_plan.md",
    "nature_physics_submission_gate_status.md",
    "nature_physics_editorial_mechanism_risk_matrix.md",
    "nature_physics_source_data_inventory.md",
    "nature_physics_figure_argument_audit.md",
    "nature_physics_numerical_claim_audit.md",
    "nature_physics_main_figure_qa.md",
    "audit_nature_physics_main_pdf_visual.py",
    "audit_nature_physics_extended_data_visual.py",
    "audit_nature_physics_numerical_claims.py",
    "nature_physics_cover_letter_draft.md",
    "nature_physics_presubmission_enquiry.md",
    "mine_unified_cold_hot_projection.py",
    "nature_physics_unified_projection_report.md",
    "mine_breathing_response_function.py",
    "nature_physics_breathing_response_function.md",
    "mine_loop_susceptibility_kernel.py",
    "nature_physics_loop_susceptibility_kernel.md",
    "mine_readout_orthogonality.py",
    "nature_physics_readout_orthogonality.md",
    "mine_training_order_parameter_flow.py",
    "nature_physics_training_order_parameter_flow.md",
    "mine_breathing_phase_diagram.py",
    "nature_physics_breathing_phase_diagram.md",
    "mine_two_scale_response_collapse.py",
    "nature_physics_two_scale_response_collapse.md",
    "mine_dynamical_mode_alignment.py",
    "nature_physics_dynamical_mode_alignment.md",
    "mine_preparation_susceptibility.py",
    "nature_physics_preparation_susceptibility.md",
    "mine_fluctuation_response_bridge.py",
    "nature_physics_fluctuation_response_bridge.md",
    "mine_force_loop_precursor_audit.py",
    "nature_physics_force_loop_precursor.md",
    "mine_causal_path_audit.py",
    "nature_physics_causal_path_audit.md",
    "mine_breathing_quality_factor.py",
    "nature_physics_breathing_quality_factor.md",
    "mine_overload_observability_response.py",
    "nature_physics_overload_observability_response.md",
    "mine_lyapunov_storage_response.py",
    "nature_physics_lyapunov_storage_response.md",
    "mine_force_loop_rare_event_risk.py",
    "nature_physics_force_loop_rare_event_risk.md",
    "mine_force_loop_rare_event_precursor.py",
    "nature_physics_force_loop_rare_event_precursor.md",
    "mine_breathing_memory_kernel.py",
    "nature_physics_breathing_memory_kernel.md",
    "mine_force_loop_enrichment_decomposition.py",
    "nature_physics_force_loop_enrichment_decomposition.md",
    "mine_breathing_memory_cost_tradeoff.py",
    "nature_physics_breathing_memory_cost_tradeoff.md",
    "mine_breathing_vital_signs.py",
    "nature_physics_breathing_vital_signs.md",
    "mine_breathing_component_necessity.py",
    "nature_physics_breathing_component_necessity.md",
    "mine_eight_route_hot_breath_cost.py",
    "nature_physics_eight_route_hot_breath_cost.md",
    "mine_return_map_normal_form.py",
    "nature_physics_return_map_normal_form.md",
    "mine_force_loop_conduit_gating.py",
    "nature_physics_force_loop_conduit_gating.md",
    "mine_force_network_snapshot_plate.py",
    "nature_physics_force_network_snapshot_plate.md",
    "mine_force_loop_spatial_fingerprint.py",
    "nature_physics_force_loop_spatial_fingerprint.md",
    "mine_eight_route_force_filtration_topology.py",
    "nature_physics_force_filtration_topology.md",
    "mine_force_filtration_shuffle_null.py",
    "nature_physics_force_filtration_shuffle_null.md",
    "mine_five_route_breath_memory_spectrum.py",
    "nature_physics_five_route_breath_memory_spectrum.md",
    "mine_two_scale_variance_partition.py",
    "nature_physics_two_scale_variance_partition.md",
    "mine_route_susceptibility_atlas.py",
    "nature_physics_route_susceptibility_atlas.md",
    "mine_phase_displacement_geometry.py",
    "nature_physics_phase_displacement_geometry.md",
    "mine_phase_circulation_geometry.py",
    "nature_physics_phase_circulation_geometry.md",
    "mine_phase_circulation_order_null.py",
    "nature_physics_phase_circulation_order_null.md",
    "mine_phase_circulation_coordinate_robustness.py",
    "nature_physics_phase_circulation_coordinate_robustness.md",
    "mine_phase_circulation_writing_time.py",
    "nature_physics_phase_circulation_writing_time.md",
    "mine_phase_circulation_synthesis.py",
    "nature_physics_phase_circulation_synthesis.md",
    "mine_loop_predictive_information.py",
    "nature_physics_loop_predictive_information.md",
    "mine_loop_information_binning_robustness.py",
    "nature_physics_loop_information_binning_robustness.md",
    "mine_loop_information_bias_corrected.py",
    "nature_physics_loop_information_bias_corrected.md",
    "mine_two_scale_information_decomposition.py",
    "nature_physics_two_scale_information_decomposition.md",
    "mine_state_closure_memory_depth.py",
    "nature_physics_state_closure_memory_depth.md",
    "select_route_generality_candidates.py",
    "nature_physics_route_generality_candidates.md",
    "nature_physics_route_generality_remote_status.md",
    "collect_route_generality_remote_manifest.py",
    "mine_route_generality_true_force_extension.py",
    "nature_physics_route_generality_true_force_extension.md",
    "nature_physics_route_generality_remote_manifest.md",
    "../scripts/run_route_generality_force_probe_remote_oneshot.sh",
    "../scripts/pull_route_generality_force_probe_results.sh",
    "../scripts/process_route_generality_when_complete.sh",
    "build_supp_fig5_long_cycle_summary.py",
    "supp_fig5_long_cycle_summary_report.md",
    "nature_physics_experimental_validation_protocol.md",
    "build_experimental_validation_protocol.py",
    "nature_physics_raw_data_archive_manifest.md",
    "build_nature_physics_archive_staging.py",
    "build_nature_physics_archive_checksums.py",
    "archive_staging/README_dataset.md",
    "archive_staging/datacite_metadata_draft.json",
    "archive_staging/figure_to_source_data_map.md",
    "archive_staging/repository_upload_checklist.md",
    "archive_staging/archive_package_plan.md",
    "archive_staging/required_raw_file_sha256.csv",
]

SOURCE_DATA = [
    "nature_physics_extended_data_crossref.csv",
    "nature_physics_extended_data_visual_qa.csv",
    "nature_physics_main_pdf_visual_qa.csv",
    "nature_physics_numerical_claim_audit.csv",
    "nphys_fig1_memory_source.csv",
    "nphys_fig2_boundary_semi_confined_source.csv",
    "nphys_fig2_boundary_precompressed_source.csv",
    "nphys_fig2_boundary_wall_profile_source.csv",
    "nature_physics_two_channel_summary_source.csv",
    "nature_physics_two_channel_seed_source.csv",
    "nphys_long_cycle_true_force_hot_cold_delta.csv",
    "nphys_return_map_phase_portrait_route_phase_summary.csv",
    "nphys_return_map_phase_portrait_route_displacements.csv",
    "nphys_return_map_phase_portrait_route_maps.csv",
    "nphys_route_phase_space_27case.csv",
    "nphys_force_loop_robustness_conditional.csv",
    "nphys_dimensionless_loop_collapse_model_tests.csv",
    "nphys_loop_onset_logistic_tests.csv",
    "nphys_mechanism_hierarchy_model_tests.csv",
    "nphys_nonreciprocal_transient_map_metrics.csv",
    "nphys_minimal_state_sufficiency_summary.csv",
    "nphys_breathing_response_function_cycle_metrics.csv",
    "nphys_breathing_response_function_correlations.csv",
    "nphys_breathing_response_function_forward_tests.csv",
    "nphys_breathing_response_function_regime_summary.csv",
    "nphys_unified_projection_six_regime.csv",
    "nphys_unified_projection_long_cycle.csv",
    "nphys_unified_projection_correlations.csv",
    "nphys_loop_susceptibility_kernel_cycle_metrics.csv",
    "nphys_loop_susceptibility_kernel_route_kernels.csv",
    "nphys_loop_susceptibility_kernel_bootstrap.csv",
    "nphys_loop_susceptibility_kernel_model_tests.csv",
    "nphys_loop_susceptibility_kernel_predictions.csv",
    "nphys_readout_orthogonality_tests.csv",
    "nphys_readout_orthogonality_regression.csv",
    "nphys_readout_orthogonality_bootstrap.csv",
    "nphys_training_order_parameter_flow_cycle_metrics.csv",
    "nphys_training_order_parameter_flow_fits.csv",
    "nphys_training_order_parameter_flow_correlations.csv",
    "nphys_breathing_phase_diagram_cycle_metrics.csv",
    "nphys_breathing_phase_diagram_correlations.csv",
    "nphys_breathing_phase_diagram_forward_tests.csv",
    "nphys_breathing_phase_diagram_route_summary.csv",
    "nphys_two_scale_response_collapse_cycle_metrics.csv",
    "nphys_two_scale_response_collapse_route_kernels.csv",
    "nphys_two_scale_response_collapse_bootstrap.csv",
    "nphys_two_scale_response_collapse_model_tests.csv",
    "nphys_two_scale_response_collapse_predictions.csv",
    "nphys_two_scale_response_collapse_metrics.csv",
    "nphys_dynamical_mode_alignment_route_modes.csv",
    "nphys_dynamical_mode_alignment_cycle_projection.csv",
    "nphys_dynamical_mode_alignment_correlations.csv",
    "nphys_dynamical_mode_alignment_model_tests.csv",
    "nphys_dynamical_mode_alignment_random_direction_null.csv",
    "nphys_preparation_susceptibility_regime_summary.csv",
    "nphys_preparation_susceptibility_tests.csv",
    "nphys_fluctuation_response_bridge_summary.csv",
    "nphys_fluctuation_response_bridge_tests.csv",
    "nphys_force_loop_precursor_lag_scan.csv",
    "nphys_force_loop_precursor_circular_shift_null.csv",
    "nphys_force_loop_precursor_forward_tests.csv",
    "nphys_force_loop_precursor_predictions.csv",
    "nphys_force_loop_precursor_route_summary.csv",
    "nphys_causal_path_partial_residuals.csv",
    "nphys_causal_path_permutation_gain.csv",
    "nphys_causal_path_permutation_null.csv",
    "nphys_causal_path_leave_one_route_models.csv",
    "nphys_causal_path_route_kernels.csv",
    "nphys_breathing_quality_factor_cycle_metrics.csv",
    "nphys_breathing_quality_factor_correlations.csv",
    "nphys_breathing_quality_factor_forward_tests.csv",
    "nphys_breathing_quality_factor_circular_shift_null.csv",
    "nphys_breathing_quality_factor_route_segments.csv",
    "nphys_overload_observability_route_metrics.csv",
    "nphys_overload_observability_cycle_projection.csv",
    "nphys_overload_observability_correlations.csv",
    "nphys_overload_observability_transfer_tests.csv",
    "nphys_lyapunov_storage_route_metrics.csv",
    "nphys_lyapunov_storage_cycle_metrics.csv",
    "nphys_lyapunov_storage_correlations.csv",
    "nphys_lyapunov_storage_transfer_tests.csv",
    "nphys_force_loop_rare_event_cycle_metrics.csv",
    "nphys_force_loop_rare_event_predictor_bins.csv",
    "nphys_force_loop_rare_event_metrics.csv",
    "nphys_force_loop_rare_event_permutation_null.csv",
    "nphys_force_loop_rare_event_route_auc.csv",
    "nphys_force_loop_rare_event_precursor_cycle_metrics.csv",
    "nphys_force_loop_rare_event_precursor_lag_scan.csv",
    "nphys_force_loop_rare_event_precursor_null.csv",
    "nphys_force_loop_rare_event_precursor_conditional_risk.csv",
    "nphys_force_loop_rare_event_precursor_route_auc.csv",
    "nphys_force_loop_rare_event_precursor_timeline.csv",
    "nphys_breathing_memory_kernel_lag_scan.csv",
    "nphys_breathing_memory_kernel_shift_null.csv",
    "nphys_breathing_memory_kernel_phase_matched_null.csv",
    "nphys_breathing_memory_kernel_transfer_tests.csv",
    "nphys_breathing_memory_kernel_coefficients.csv",
    "nphys_breathing_memory_kernel_autocorrelation.csv",
    "nphys_force_loop_enrichment_cycle_metrics.csv",
    "nphys_force_loop_enrichment_correlations.csv",
    "nphys_force_loop_enrichment_transfer_tests.csv",
    "nphys_force_loop_enrichment_route_summary.csv",
    "nphys_force_loop_conduit_gating_cycle_metrics.csv",
    "nphys_force_loop_conduit_gating_correlations.csv",
    "nphys_force_loop_conduit_gating_transfer_tests.csv",
    "nphys_force_loop_conduit_gating_conditional_risk.csv",
    "nphys_force_loop_conduit_gating_gate_tests.csv",
    "nphys_force_loop_conduit_gating_auc.csv",
    "nphys_force_loop_conduit_gating_route_summary.csv",
    "nphys_force_network_snapshot_plate_edges.csv",
    "nphys_force_network_snapshot_plate_summary.csv",
    "nphys_force_loop_spatial_fingerprint_state_metrics.csv",
    "nphys_force_loop_spatial_fingerprint_cycle_delta.csv",
    "nphys_force_loop_spatial_fingerprint_correlations.csv",
    "nphys_force_loop_spatial_fingerprint_transfer_tests.csv",
    "nphys_force_loop_spatial_fingerprint_route_summary.csv",
    "nphys_force_filtration_topology_state_metrics.csv",
    "nphys_force_filtration_topology_curves.csv",
    "nphys_force_filtration_topology_cycle_delta.csv",
    "nphys_force_filtration_topology_correlations.csv",
    "nphys_force_filtration_topology_transfer_tests.csv",
    "nphys_force_filtration_topology_route_summary.csv",
    "nphys_force_filtration_shuffle_null_state_metrics.csv",
    "nphys_force_filtration_shuffle_null_cycle_delta.csv",
    "nphys_force_filtration_shuffle_null_distribution.csv",
    "nphys_force_filtration_shuffle_null_summary.csv",
    "nphys_five_route_breath_memory_spectrum_cycle_metrics.csv",
    "nphys_five_route_breath_memory_spectrum_lag_scan.csv",
    "nphys_five_route_breath_memory_spectrum_transfer_tests.csv",
    "nphys_five_route_breath_memory_spectrum_kernel_coefficients.csv",
    "nphys_five_route_breath_memory_spectrum_parity.csv",
    "nphys_five_route_breath_memory_spectrum_route_summary.csv",
    "nphys_breathing_memory_cost_tradeoff_cycle_metrics.csv",
    "nphys_breathing_memory_cost_tradeoff_segment_summary.csv",
    "nphys_breathing_memory_cost_tradeoff_correlations.csv",
    "nphys_breathing_vital_signs_cycle_metrics.csv",
    "nphys_breathing_vital_signs_segment_summary.csv",
    "nphys_breathing_vital_signs_correlations.csv",
    "nphys_breathing_vital_signs_model_tests.csv",
    "nphys_breathing_vital_signs_shift_null.csv",
    "nphys_breathing_component_necessity_forward.csv",
    "nphys_breathing_component_necessity_route_heldout.csv",
    "nphys_breathing_component_necessity_bootstrap.csv",
    "nphys_eight_route_hot_breath_cost_cycle_metrics.csv",
    "nphys_eight_route_hot_breath_cost_tests.csv",
    "nphys_eight_route_hot_breath_cost_models.csv",
    "nphys_eight_route_hot_breath_cost_route_summary.csv",
    "nphys_return_map_normal_form_route_metrics.csv",
    "nphys_return_map_normal_form_eigenvalues.csv",
    "nphys_return_map_normal_form_lag_bridge.csv",
    "nphys_return_map_normal_form_parity_summary.csv",
    "nphys_return_map_normal_form_correlations.csv",
    "nphys_two_scale_variance_partition_cycle_metrics.csv",
    "nphys_two_scale_variance_partition_model_tests.csv",
    "nphys_two_scale_variance_partition_predictions.csv",
    "nphys_two_scale_variance_partition_shapley.csv",
    "nphys_two_scale_variance_partition_shuffle_tests.csv",
    "nphys_two_scale_variance_partition_shuffle_null.csv",
    "nphys_two_scale_variance_partition_coefficients.csv",
    "nphys_two_scale_variance_partition_route_gain.csv",
    "nphys_route_susceptibility_atlas.csv",
    "nphys_route_susceptibility_atlas_heatmap.csv",
    "nphys_route_susceptibility_atlas_correlations.csv",
    "nphys_phase_displacement_geometry.csv",
    "nphys_phase_displacement_geometry_correlations.csv",
    "nphys_phase_circulation_geometry.csv",
    "nphys_phase_circulation_geometry_segments.csv",
    "nphys_phase_circulation_geometry_correlations.csv",
    "nphys_phase_circulation_order_null_rho.csv",
    "nphys_phase_circulation_order_null_route.csv",
    "nphys_phase_circulation_order_null_summary.csv",
    "nphys_phase_circulation_coordinate_robustness_route.csv",
    "nphys_phase_circulation_coordinate_robustness_correlations.csv",
    "nphys_phase_circulation_coordinate_robustness_summary.csv",
    "nphys_phase_circulation_writing_time_curves.csv",
    "nphys_phase_circulation_writing_time_summary.csv",
    "nphys_phase_circulation_writing_time_correlations.csv",
    "nphys_phase_circulation_synthesis_route_metrics.csv",
    "nphys_phase_circulation_synthesis_control_metrics.csv",
    "nphys_loop_predictive_information_spectrum.csv",
    "nphys_loop_predictive_information_shift_null.csv",
    "nphys_loop_predictive_information_conditional.csv",
    "nphys_loop_predictive_information_route_summary.csv",
    "nphys_loop_information_binning_robustness_sweep.csv",
    "nphys_loop_information_binning_robustness_shift_null.csv",
    "nphys_loop_information_binning_robustness_conditional.csv",
    "nphys_loop_information_binning_robustness_summary.csv",
    "nphys_loop_information_bias_corrected_sweep.csv",
    "nphys_loop_information_bias_corrected_bootstrap.csv",
    "nphys_loop_information_bias_corrected_summary.csv",
    "nphys_two_scale_information_decomposition.csv",
    "nphys_two_scale_information_decomposition_shift_null.csv",
    "nphys_two_scale_information_decomposition_summary.csv",
    "nphys_state_closure_model_tests.csv",
    "nphys_state_closure_predictions.csv",
    "nphys_state_closure_incremental.csv",
    "nphys_state_closure_residual_memory.csv",
    "nphys_state_closure_summary.csv",
    "nphys_route_generality_candidates.csv",
    "nphys_route_generality_remote_manifest.csv",
    "nphys_route_generality_true_force_extension_metrics.csv",
    "nphys_route_generality_true_force_extension_delta.csv",
    "nphys_route_generality_true_force_extension_completeness.csv",
    "nphys_route_generality_true_force_extension_tests.csv",
    "nphys_experimental_prediction_matrix.csv",
    "nphys_experimental_validation_protocol.csv",
    "nature_physics_raw_data_archive_inventory.csv",
    "fig5_long_cycle_source.csv",
    "fig5_long_cycle_stats.json",
]


def record(rows: list[dict[str, str]], group: str, item: str, path: Path, required: str = "yes") -> None:
    exists = path.exists()
    size = path.stat().st_size if exists else 0
    status = "pass" if exists and size > 0 else "missing_or_empty"
    rows.append(
        {
            "group": group,
            "item": item,
            "path": str(path.relative_to(ROOT)),
            "required": required,
            "exists": str(exists),
            "size_bytes": str(size),
            "status": status,
        }
    )


def main() -> None:
    rows: list[dict[str, str]] = []
    for name in MANUSCRIPT_FILES:
        record(rows, "manuscript_package", name, ROOT / name)
    for name in MAIN_FIGURES:
        for ext in ["pdf", "png", "svg", "tiff"]:
            record(rows, "main_figure", f"{name}.{ext}", FIG / f"{name}.{ext}")
    for name in EXTENDED_FIGURES:
        for ext in ["pdf", "png", "svg", "tiff"]:
            record(rows, "extended_data_figure", f"{name}.{ext}", FIG / f"{name}.{ext}")
    for name in SUPPLEMENT_FIGURES:
        for ext in ["pdf", "png", "svg", "tiff"]:
            record(rows, "supplement_figure", f"{name}.{ext}", FIG / f"{name}.{ext}")
    for name in RESERVE_FIGURES:
        for ext in ["pdf", "png", "svg", "tiff"]:
            record(rows, "reserve_figure", f"{name}.{ext}", FIG / f"{name}.{ext}")
    for name in SOURCE_DATA:
        record(rows, "source_data", name, SRC / name)

    OUT_CSV.parent.mkdir(exist_ok=True)
    with OUT_CSV.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    failures = [r for r in rows if r["status"] != "pass" and r["required"] == "yes"]
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["group"]] = counts.get(r["group"], 0) + 1
    lines = [
        "# Nature Physics submission asset audit",
        "",
        f"Checked {len(rows)} required artifacts across {len(counts)} package groups.",
        "",
        "## Group counts",
        "",
    ]
    for group, count in sorted(counts.items()):
        lines.append(f"- {group}: {count}")
    lines.extend(["", "## Result", ""])
    if failures:
        lines.append(f"Status: FAIL, {len(failures)} missing or empty required artifacts.")
        lines.append("")
        for r in failures:
            lines.append(f"- {r['group']} | {r['path']} | {r['status']}")
    else:
        lines.append("Status: PASS, all required manuscript, figure and source-data artifacts exist and are non-empty.")
    lines.extend(["", f"Machine-readable audit: `{OUT_CSV.relative_to(ROOT)}`", ""])
    OUT_MD.write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
